# Generated by Django 3.2.25 on 2024-07-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_salestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksale',
            name='discounted',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stocksale',
            name='total_order_count',
            field=models.IntegerField(default=1),
        ),
    ]
