# Generated by Django 3.2.25 on 2024-07-04 11:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_salestock', '0003_stocksale_client_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksale',
            name='discounted',
        ),
        migrations.AddField(
            model_name='stocksale',
            name='after_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stocksale',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocksale',
            name='client_payed',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocksale',
            name='total_order_count',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
