# Generated by Django 3.2.25 on 2024-07-04 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trouser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutt_no', models.CharField(max_length=50)),
                ('wash', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('piece_style', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('manufacturing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=10)),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='T_shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manafacturing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutt_no', models.CharField(max_length=50)),
                ('wash', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('piece_style', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('manufacturing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=10)),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manafacturing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutt_no', models.CharField(max_length=50)),
                ('wash', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('piece_style', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('manufacturing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=10)),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Jacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manafacturing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
