# Generated by Django 3.2.25 on 2024-08-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jacket',
            name='brand_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pant',
            name='brand_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shorts',
            name='brand_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trouser',
            name='brand_name',
            field=models.CharField(max_length=100),
        ),
    ]
