# Generated by Django 3.2.25 on 2024-08-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20240802_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='jacket',
            name='total_pice_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pant',
            name='total_pcs_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pant',
            name='wash_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirt',
            name='total_pice_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shorts',
            name='total_pcs_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shorts',
            name='wash_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_shirt',
            name='total_pice_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trouser',
            name='total_pcs_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trouser',
            name='wash_type',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
