# Generated by Django 3.2.25 on 2024-08-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20240809_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='pant',
            name='set_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorts',
            name='set_quantity',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trouser',
            name='set_quantity',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
