# Generated by Django 3.2.25 on 2024-07-04 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joining_date', models.DateField(default=datetime.date.today)),
                ('department', models.CharField(default='General', max_length=100)),
                ('gender', models.CharField(default='Not Specified', max_length=10)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('date_of_birth', models.DateField(default=datetime.date(2000, 1, 1))),
                ('description', models.TextField(default='No description provided')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('sms', models.CharField(blank=True, max_length=15, null=True)),
                ('idcard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('original_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('absences', models.IntegerField(default=0)),
                ('late_arrivals', models.IntegerField(default=0)),
                ('presents', models.IntegerField(default=0)),
                ('leaves', models.IntegerField(default=0)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remaining_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salaries', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('absent', models.BooleanField(default=False)),
                ('on_leave', models.BooleanField(default=False)),
                ('late', models.BooleanField(default=False)),
                ('on_time', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
