# Generated by Django 3.2.25 on 2024-07-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_salarydetection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydetection',
            name='detect_on_absent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salarydetection',
            name='detect_on_late',
            field=models.IntegerField(),
        ),
    ]
